var tvData = [
 // {
 //   "Title": "Shadowhunters: The Mortal Instruments",
 //   "Mood": "adventure",
 //   "Your Rating": 4,
 //   "Title Type": "tvSeries",
 //   "IMDb Rating": 6.6,
 //   "Genres": "Action, Fantasy, Romance",
 //   "Release Date": "2016-01-12",
 //   "Directors": "",
 //   "Year": 2016,
 //   "URL": "https://www.imdb.com/title/tt4145054/",
 //   "image": "https://m.media-amazon.com/images/M/MV5BMTgwMzM3NjQzN15BMl5BanBnXkFtZTgwMjgxMDQ5NDM@._V1_SY1000_CR0,0,675,1000_AL_.jpg"
 // },
 {
   "Title": "Fuller House",
   "Mood": "family",
   "Your Rating": 5,
   "Title Type": "tvSeries",
   "IMDb Rating": 6.9,
   "Genres": "Comedy, Family",
   "Release Date": "2016-02-26",
   "Directors": "",
   "Year": 2016,
   "URL": "https://www.imdb.com/title/tt3986586/",
   "image": "https://m.media-amazon.com/images/M/MV5BMjAxMzU5MzA0MF5BMl5BanBnXkFtZTgwODgyOTg1MzI@._V1_SY1000_CR0,0,674,1000_AL_.jpg"
 },
 {
   "Title": "Pretty Little Liars",
   "Mood": "dark",
   "Your Rating": 6,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.5,
   "Genres": "Drama, Mystery, Romance, Thriller",
   "Release Date": "2010-06-08",
   "Directors": "",
   "Year": 2010,
   "URL": "https://www.imdb.com/title/tt1578873/",
   "image": "https://m.media-amazon.com/images/M/MV5BMTU5MDYzMzQ2Nl5BMl5BanBnXkFtZTgwMDE3MzU4MTI@._V1_SY1000_CR0,0,678,1000_AL_.jpg"
 },
 {
   "Title": "Unbreakable Kimmy Schmidt",
   "Mood": "laugh",
   "Your Rating": 6,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.7,
   "Genres": "Comedy, Drama",
   "Release Date": "2015-03-06",
   "Directors": "",
   "Year": 2015,
   "URL": "https://www.imdb.com/title/tt3339966/",
   "image": "https://m.media-amazon.com/images/M/MV5BMjI1Mzg0MzY1MF5BMl5BanBnXkFtZTgwMjcxNjg0ODE@._V1_.jpg"
 },
 {
   "Title": "The OA",
   "Mood": "dark",
   "Your Rating": 6,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.8,
   "Genres": "Drama, Fantasy, Mystery, Sci-Fi",
   "Release Date": "2016-12-16",
   "Directors": "",
   "Year": 2016,
   "URL": "https://www.imdb.com/title/tt4635282/",
   "image": "https://m.media-amazon.com/images/M/MV5BMTc3MjA5NDM5N15BMl5BanBnXkFtZTgwOTgzNTQ4MDI@._V1_SY1000_CR0,0,674,1000_AL_.jpg"
 },
 {
   "Title": "Stitchers",
   "Mood": "think",
   "Your Rating": 6,
   "Title Type": "tvSeries",
   "IMDb Rating": 7,
   "Genres": "Crime, Drama, SciFi",
   "Release Date": "2015-06-02",
   "Directors": "",
   "Year": 2015,
   "URL": "https://www.imdb.com/title/tt3868848/",
   "image": "https://m.media-amazon.com/images/M/MV5BMjM4MzU1MTMzOF5BMl5BanBnXkFtZTgwMzY1ODI4NTE@._V1_.jpg"
 },
 {
   "Title": "Once Upon a Time",
   "Mood": "adventure",
   "Your Rating": 6,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.8,
   "Genres": "Adventure, Fantasy, Romance",
   "Release Date": "2011-10-23",
   "Directors": "",
   "Year": 2011,
   "URL": "https://www.imdb.com/title/tt1843230/",
   "image": "https://m.media-amazon.com/images/M/MV5BNjBmZmI0ZDktODI2MS00MDU1LTk0NDYtNGE0MDc0OWVkYzcwXkEyXkFqcGdeQXVyMzAzNTY3MDM@._V1_SY1000_SX675_AL_.jpg"
 },
 {
   "Title": "Wet Hot American Summer: Ten Years Later",
   "Mood": "laugh",
   "Your Rating": 6,
   "Title Type": "tvSeries",
   "IMDb Rating": 7,
   "Genres": "Comedy",
   "Release Date": "2017-08-04",
   "Directors": "",
   "Year": 2017,
   "URL": "https://www.imdb.com/title/tt5669272/",
   "image": "https://m.media-amazon.com/images/M/MV5BMjExMTQ0NTE3Ml5BMl5BanBnXkFtZTgwNDEzOTc4MjI@._V1_.jpg"
 },
 {
   "Title": "The Fosters",
   "Mood": "cry",
   "Your Rating": 7,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.9,
   "Genres": "Drama, Romance",
   "Release Date": "2013-06-03",
   "Directors": "",
   "Year": 2013,
   "URL": "https://www.imdb.com/title/tt2262532/",
   "image": "https://m.media-amazon.com/images/M/MV5BMGNjMTRjMjItYzUzNi00Mzk1LWFkM2MtNmZlODdjZGUwYTQzXkEyXkFqcGdeQXVyNjc4MzM4NTM@._V1_.jpg"
 },
 {
   "Title": "Stranger Things",
   "Mood": "adventure",
   "Your Rating": 7,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.9,
   "Genres": "Drama, Fantasy, Horror, Mystery, Sci-Fi, Thriller",
   "Release Date": "2016-07-11",
   "Directors": "",
   "Year": 2016,
   "URL": "https://www.imdb.com/title/tt4574334/",
   "image": "https://m.media-amazon.com/images/M/MV5BMjUwMDgzOTg3Nl5BMl5BanBnXkFtZTgwNTI4MDk5MzI@._V1_SY1000_CR0,0,669,1000_AL_.jpg"
 },
 {
   "Title": "Cuckoo",
   "Mood": "laugh",
   "Your Rating": 7,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.4,
   "Genres": "Comedy",
   "Release Date": "2012-09-25",
   "Directors": "",
   "Year": 2012,
   "URL": "https://www.imdb.com/title/tt2222352/",
   "image": "https://m.media-amazon.com/images/M/MV5BMzY0ODI2OTY3OF5BMl5BanBnXkFtZTgwNDkwNTU3MzE@._V1_SY1000_CR0,0,707,1000_AL_.jpg"
 },
 {
   "Title": "The Walking Dead",
   "Mood": "gross",
   "Your Rating": 7,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.4,
   "Genres": "Drama, Horror, Sci-Fi, Thriller",
   "Release Date": "2010-10-31",
   "Directors": "",
   "Year": 2010,
   "URL": "https://www.imdb.com/title/tt1520211/",
   "image": "https://m.media-amazon.com/images/M/MV5BMTcwMDAzMDk3OF5BMl5BanBnXkFtZTgwMjY0MzcyNjM@._V1_SY1000_CR0,0,674,1000_AL_.jpg"
 },
 {
   "Title": "Scandal",
   "Mood": "love",
   "Your Rating": 7,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.8,
   "Genres": "Drama, Thriller",
   "Release Date": "2012-04-05",
   "Directors": "",
   "Year": 2012,
   "URL": "https://www.imdb.com/title/tt1837576/",
   "image": "https://m.media-amazon.com/images/M/MV5BMTUxNzk3MDQyNl5BMl5BanBnXkFtZTgwNDgxMDkyMzI@._V1_SY1000_CR0,0,674,1000_AL_.jpg"
 },
 {
   "Title": "The Originals",
   "Mood": "adventure",
   "Your Rating": 7,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.3,
   "Genres": "Drama, Fantasy, Horror, Mystery",
   "Release Date": "2013-10-03",
   "Directors": "",
   "Year": 2013,
   "URL": "https://www.imdb.com/title/tt2632424/",
   "image": "https://m.media-amazon.com/images/M/MV5BMTA2YjViYzctMjZjNi00YzZjLWE0ZjEtYTJkZTY0OTI3NjQ5XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SY1000_CR0,0,701,1000_AL_.jpg"
 },
 {
   "Title": "Bones",
   "Mood": "adventure",
   "Your Rating": 7,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.9,
   "Genres": "Comedy, Crime, Drama",
   "Release Date": "2005-09-13",
   "Directors": "",
   "Year": 2005,
   "URL": "https://www.imdb.com/title/tt0460627/",
   "image": "https://m.media-amazon.com/images/M/MV5BMjA3ODMxMzM5NF5BMl5BanBnXkFtZTgwMDM1NjU0OTE@._V1_SY1000_CR0,0,647,1000_AL_.jpg"
 },
 {
   "Title": "Grey's Anatomy",
   "Mood": "cry",
   "Your Rating": 7,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.6,
   "Genres": "Drama, Romance",
   "Release Date": "2005-03-27",
   "Directors": "",
   "Year": 2005,
   "URL": "https://www.imdb.com/title/tt0413573/",
   "image": "https://m.media-amazon.com/images/M/MV5BMTY5OTNjNTctMWYxNC00YjE2LWEzMTMtMTIzMzQ1MzhkODRhXkEyXkFqcGdeQXVyMzAzNTY3MDM@._V1_SY1000_SX675_AL_.jpg"
 },
 {
   "Title": "Riverdale",
   "Mood": "big",
   "Your Rating": 7,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.6,
   "Genres": "Crime, Drama, Mystery, Romance",
   "Release Date": "2016-07-21",
   "Directors": "",
   "Year": 2016,
   "URL": "https://www.imdb.com/title/tt5420376/",
   "image": "https://m.media-amazon.com/images/M/MV5BYTNhZGU3YjAtMzg0OC00ZjdlLWIwYzItNzBjYjhkNWFkZWViXkEyXkFqcGdeQXVyMjYwNDA2MDE@._V1_SY1000_CR0,0,682,1000_AL_.jpg"
 },
 {
   "Title": "Modern Family",
   "Mood": "laugh",
   "Your Rating": 7,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.5,
   "Genres": "Comedy, Romance",
   "Release Date": "2009-09-22",
   "Directors": "",
   "Year": 2009,
   "URL": "https://www.imdb.com/title/tt1442437/",
   "image": "https://m.media-amazon.com/images/M/MV5BMTU2NTU3OTE5NF5BMl5BanBnXkFtZTgwMDAzMjE1NjM@._V1_SY1000_CR0,0,675,1000_AL_.jpg"
 },
 {
   "Title": "Good Girls",
   "Mood": "laugh",
   "Your Rating": 7,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.9,
   "Genres": "Comedy, Crime, Drama",
   "Release Date": "2018-02-26",
   "Directors": "",
   "Year": 2018,
   "URL": "https://www.imdb.com/title/tt6474378",
   "image": "https://m.media-amazon.com/images/M/MV5BNDA4MGQ5YzQtYWRhNy00ZTM2LWJlYWUtM2RmODg2YjA0ZDVmXkEyXkFqcGdeQXVyNjMxNzcwOTI@._V1_.jpg"
 },
 {
   "Title": "Haters Back Off!",
   "Mood": "gross",
   "Your Rating": 7,
   "Title Type": "tvSeries",
   "IMDb Rating": 6.1,
   "Genres": "Comedy, Drama, Romance",
   "Release Date": "2016-10-14",
   "Directors": "",
   "Year": 2016,
   "URL": "https://www.imdb.com/title/tt5467814/",
   "image": "https://m.media-amazon.com/images/M/MV5BMjMzNzEwNDIzNl5BMl5BanBnXkFtZTgwMzI4OTMyMDI@._V1_.jpg"
 },
 {
   "Title": "Teen Wolf",
   "Mood": "adventure",
   "Your Rating": 7,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.7,
   "Genres": "Action, Comedy, Drama, Fantasy, Horror, Romance, Thriller",
   "Release Date": "2011-06-05",
   "Directors": "",
   "Year": 2011,
   "URL": "https://www.imdb.com/title/tt1567432/",
   "image": "https://m.media-amazon.com/images/M/MV5BMTEwMzcyMjYwNzNeQTJeQWpwZ15BbWU4MDAwMTU2ODIy._V1_.jpg"
 },
 {
   "Title": "The Vampire Diaries",
   "Mood": "love",
   "Your Rating": 8,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.7,
   "Genres": "Drama, Fantasy, Horror, Mystery, Romance, Thriller",
   "Release Date": "2009-09-10",
   "Directors": "",
   "Year": 2009,
   "URL": "https://www.imdb.com/title/tt1405406/",
   "image": "https://m.media-amazon.com/images/M/MV5BODhiODk3NWEtZmNiYi00N2NlLThlN2YtN2VkYTYyMjQxMWEzXkEyXkFqcGdeQXVyNjU2NjA5NjM@._V1_SY1000_CR0,0,710,1000_AL_.jpg"
 },
 {
   "Title": "Bates Motel",
   "Mood": "dark",
   "Your Rating": 8,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.2,
   "Genres": "Drama, Horror, Mystery, Thriller",
   "Release Date": "2013-03-18",
   "Directors": "",
   "Year": 2013,
   "URL": "https://www.imdb.com/title/tt2188671/",
   "image": "https://m.media-amazon.com/images/M/MV5BMzk4OTU5NTE2M15BMl5BanBnXkFtZTcwNTIxMDIyOQ@@._V1_SY1000_CR0,0,750,1000_AL_.jpg"
 },
 // {
 //   "Title": "Jessica Jones",
 //   "Mood": "dark",
 //   "Your Rating": 8,
 //   "Title Type": "tvSeries",
 //   "IMDb Rating": 8.1,
 //   "Genres": "Action, Crime, Drama, Sci-Fi, Thriller",
 //   "Release Date": "2015-10-10",
 //   "Directors": "",
 //   "Year": 2015,
 //   "URL": "https://www.imdb.com/title/tt2357547/",
 //   "image": "https://m.media-amazon.com/images/M/MV5BMTkxMDk5NTQ3MF5BMl5BanBnXkFtZTgwNzg3ODU3NDM@._V1_SY1000_CR0,0,674,1000_AL_.jpg"
 // },
 {
   "Title": "Gilmore Girls",
   "Mood": "laugh",
   "Your Rating": 8,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.1,
   "Genres": "Comedy, Drama",
   "Release Date": "2000-10-05",
   "Directors": "",
   "Year": 2000,
   "URL": "https://www.imdb.com/title/tt0238784/",
   "image": "https://m.media-amazon.com/images/M/MV5BMTQ3NDA1ZWYtYjBmMC00NmJjLWI1NjgtYjg2NDhmMTY2YWQ4XkEyXkFqcGdeQXVyNzA5NjUyNjM@._V1_.jpg"
 },
 {
   "Title": "How to Get Away with Murder",
   "Mood": "think",
   "Your Rating": 8,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.2,
   "Genres": "Crime, Drama, Mystery, Thriller",
   "Release Date": "2014-09-25",
   "Directors": "",
   "Year": 2014,
   "URL": "https://www.imdb.com/title/tt3205802/",
   "image": "https://m.media-amazon.com/images/M/MV5BMjMzNzM1MDI4NV5BMl5BanBnXkFtZTgwNjk1OTYzNjM@._V1_SY1000_CR0,0,675,1000_AL_.jpg"
 },
 {
   "Title": "UnREAL",
   "Mood": "dark",
   "Your Rating": 8,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.9,
   "Genres": "Drama",
   "Release Date": "2015-06-01",
   "Directors": "",
   "Year": 2015,
   "URL": "https://www.imdb.com/title/tt3314218/",
   "image": "https://m.media-amazon.com/images/M/MV5BZmM2MDg3ZTctNmE4My00YmZjLTkyZGEtODZkMDU4ZjQ3ZDM2XkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_SY1000_SX750_AL_.jpg"
 },
 {
   "Title": "The Tonight Show Starring Jimmy Fallon",
   "Mood": "sleep",
   "Your Rating": 8,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.5,
   "Genres": "Comedy, Music, Talk-Show",
   "Release Date": "2014-02-17",
   "Directors": "",
   "Year": 2014,
   "URL": "https://www.imdb.com/title/tt3444938/",
   "image": "https://m.media-amazon.com/images/M/MV5BOGExZGZkMTQtMDBhMy00ZDExLWFkMjktMDU4YzJmNzJjNTdmXkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_.jpg"
 },
 {
   "Title": "Scream: The TV Series",
   "Mood": "fear",
   "Your Rating": 8,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.3,
   "Genres": "Crime, Drama, Horror, Mystery, Thriller",
   "Release Date": "2015-06-30",
   "Directors": "",
   "Year": 2015,
   "URL": "https://www.imdb.com/title/tt3921180/",
   "image": "https://m.media-amazon.com/images/M/MV5BNjVmY2M3ZTUtMDhkZC00ODk4LTkwMjktNDRjNGRjYTIxZGZiXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_.jpg"
 },
 {
   "Title": "How I Met Your Mother",
   "Mood": "laugh",
   "Your Rating": 8,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.3,
   "Genres": "Comedy, Romance",
   "Release Date": "2005-09-19",
   "Directors": "",
   "Year": 2005,
   "URL": "https://www.imdb.com/title/tt0460649/",
   "image": "https://m.media-amazon.com/images/M/MV5BMTA5MzAzNTcyNjZeQTJeQWpwZ15BbWU3MDUyMzE1MTk@._V1_.jpg"
 },
 {
   "Title": "The Show About the Show",
   "Mood": "laugh",
   "Your Rating": 8,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.5,
   "Genres": "Comedy",
   "Release Date": "2015-10-05",
   "Directors": "",
   "Year": 2015,
   "URL": "https://www.imdb.com/title/tt5097492/",
   "image": "https://m.media-amazon.com/images/M/MV5BMTQ2OTMyMTM4MF5BMl5BanBnXkFtZTgwMzE4MjQ1NzE@._V1_SY1000_CR0,0,666,1000_AL_.jpg"
 },
 {
   "Title": "Saturday Night Live",
   "Mood": "laugh",
   "Your Rating": 8,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.1,
   "Genres": "Comedy, Music",
   "Release Date": "1975-10-11",
   "Directors": "",
   "Year": 1975,
   "URL": "https://www.imdb.com/title/tt0072562",
   "image": "https://m.media-amazon.com/images/M/MV5BNjM3OTFhMjUtMDlkMC00NGQ5LTgxNDMtNGY2YjRmNzljMmRmXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SY1000_CR0,0,666,1000_AL_.jpg"
 },
 {
   "Title": "House of Cards",
   "Mood": "dark",
   "Your Rating": 8,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.9,
   "Genres": "Drama",
   "Release Date": "2013-02-01",
   "Directors": "",
   "Year": 2013,
   "URL": "https://www.imdb.com/title/tt1856010/",
   "image": "https://m.media-amazon.com/images/M/MV5BODM1MDU2NjY5NF5BMl5BanBnXkFtZTgwMDkxNTcwNjM@._V1_SY1000_CR0,0,674,1000_AL_.jpg"
 },
 {
   "Title": "Charmed",
   "Mood": "adventure",
   "Your Rating": 8,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.1,
   "Genres": "Drama, Fantasy, Mystery,",
   "Release Date": "1998-10-07",
   "Directors": "",
   "Year": 1998,
   "URL": "https://www.imdb.com/title/tt0158552",
   "image": "https://m.media-amazon.com/images/M/MV5BNTIxNmUxMWQtNjc0Yy00NjM2LWFjMTMtNjA2MmEzOTFiMWRmXkEyXkFqcGdeQXVyNzA5NjUyNjM@._V1_.jpg"
 },
 {
   "Title": "Stalker",
   "Mood": "dark",
   "Your Rating": 8,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.6,
   "Genres": "Crime, Drama, Thriller",
   "Release Date": "2014-10-01",
   "Directors": "",
   "Year": 2014,
   "URL": "https://www.imdb.com/title/tt3560094/",
   "image": "https://m.media-amazon.com/images/M/MV5BMTQ4OTk3NDI2M15BMl5BanBnXkFtZTgwODcyNzE4MjE@._V1_SY1000_CR0,0,666,1000_AL_.jpg"
 },
 {
   "Title": "The X-Files",
   "Mood": "adventure",
   "Your Rating": 8,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.7,
   "Genres": "Drama, Mystery, SciFi",
   "Release Date": "1993-09-10",
   "Directors": "",
   "Year": 1993,
   "URL": "https://www.imdb.com/title/tt0106179/",
   "image": "https://m.media-amazon.com/images/M/MV5BNzE4Njg5ODk0OV5BMl5BanBnXkFtZTgwOTU0MzAyNDM@._V1_SY1000_CR0,0,674,1000_AL_.jpg"
 },
 {
   "Title": "Sharp Objects",
   "Mood": "fear",
   "Your Rating": 8,
   "Title Type": "tvMiniSeries",
   "IMDb Rating": 8.3,
   "Genres": "Crime, Drama, Mystery, Thriller",
   "Release Date": "2018-07-08",
   "Directors": "",
   "Year": 2018,
   "URL": "https://www.imdb.com/title/tt2649356/",
   "image": "https://m.media-amazon.com/images/M/MV5BZDk2NzY1MGQtYTA2MS00ZDcxLWJiMzYtNWRmMGU3ZjQ0YTFjXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SY1000_SX675_AL_.jpg"
 },
 {
   "Title": "Gilmore Girls: A Year in the Life",
   "Mood": "big",
   "Your Rating": 8,
   "Title Type": "tvMiniSeries",
   "IMDb Rating": 7.9,
   "Genres": "Comedy, Drama",
   "Release Date": "2016-11-10",
   "Directors": "",
   "Year": 2016,
   "URL": "https://www.imdb.com/title/tt5435008/",
   "image": "https://m.media-amazon.com/images/M/MV5BODM1OTk4MDY2M15BMl5BanBnXkFtZTgwOTEwNzczMDI@._V1_SY1000_CR0,0,674,1000_AL_.jpg"
 },
 {
   "Title": "Friends",
   "Mood": "laugh",
   "Your Rating": 9,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.9,
   "Genres": "Comedy, Romance",
   "Release Date": "1994-09-22",
   "Directors": "",
   "Year": 1994,
   "URL": "https://www.imdb.com/title/tt0108778/",
   "image": "https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg"
 },
 {
   "Title": "Parks and Recreation",
   "Mood": "laugh",
   "Your Rating": 9,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.6,
   "Genres": "Comedy",
   "Release Date": "2009-04-09",
   "Directors": "",
   "Year": 2009,
   "URL": "https://www.imdb.com/title/tt1266020/",
   "image": "https://m.media-amazon.com/images/M/MV5BMjA5MjUxNDgwNF5BMl5BanBnXkFtZTgwMDI5NjMwNDE@._V1_.jpg"
 },
 {
   "Title": "Whose Line Is It Anyway?",
   "Mood": "sleep",
   "Your Rating": 9,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.5,
   "Genres": "Comedy, Game-Show",
   "Release Date": "1998-08-05",
   "Directors": "",
   "Year": 1998,
   "URL": "https://www.imdb.com/title/tt0163507/",
   "image": "https://m.media-amazon.com/images/M/MV5BYmJjMTVhYjQtMjBmMC00NWYxLTk2YmEtYWIxZDUzYjljZTYxXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SY1000_CR0,0,679,1000_AL_.jpg"
 },
 {
   "Title": "The Lying Game",
   "Mood": "think",
   "Your Rating": 9,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.4,
   "Genres": "Drama, Mystery",
   "Release Date": "2011-08-15",
   "Directors": "",
   "Year": 2011,
   "URL": "https://www.imdb.com/title/tt1798274/",
   "image": "https://m.media-amazon.com/images/M/MV5BYmM3MTkyODctYmViNC00OTZmLTllNDQtMjQxZWFmNGIzMjQ4XkEyXkFqcGdeQXVyMTkzODUwNzk@._V1_SY1000_CR0,0,749,1000_AL_.jpg"
 },
 {
   "Title": "American Horror Story",
   "Mood": "fear",
   "Your Rating": 9,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.1,
   "Genres": "Drama, Horror, Thriller",
   "Release Date": "2011-10-05",
   "Directors": "",
   "Year": 2011,
   "URL": "https://www.imdb.com/title/tt1844624/",
   "image": "https://m.media-amazon.com/images/M/MV5BNTIzNDM1NjkwOV5BMl5BanBnXkFtZTgwNDU4ODgxNjM@._V1_.jpg"
 },
 {
   "Title": "The Mindy Project",
   "Mood": "love",
   "Your Rating": 9,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.4,
   "Genres": "Comedy",
   "Release Date": "2012-09-25",
   "Directors": "",
   "Year": 2012,
   "URL": "https://www.imdb.com/title/tt2211129/",
   "image": "https://m.media-amazon.com/images/M/MV5BMjAzMTQzMzc0N15BMl5BanBnXkFtZTgwOTcyMDM1MzI@._V1_.jpg"
 },
 {
   "Title": "Chasing Life",
   "Mood": "cry",
   "Your Rating": 9,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.9,
   "Genres": "Drama, Family, Romance",
   "Release Date": "2014-06-10",
   "Directors": "",
   "Year": 2014,
   "URL": "https://www.imdb.com/title/tt2399794/",
   "image": "https://m.media-amazon.com/images/M/MV5BOTczNDY1MjExM15BMl5BanBnXkFtZTgwMDc3NjMxMjE@._V1_SY1000_CR0,0,750,1000_AL_.jpg"
 },
 {
   "Title": "Brooklyn Nine-Nine",
   "Mood": "laugh",
   "Your Rating": 9,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.4,
   "Genres": "Comedy, Crime",
   "Release Date": "2013-09-17",
   "Directors": "",
   "Year": 2013,
   "URL": "https://www.imdb.com/title/tt2467372/",
   "image": "https://m.media-amazon.com/images/M/MV5BNDc3NzQxODAwOV5BMl5BanBnXkFtZTgwODkwMjU2MzI@._V1_SY1000_CR0,0,674,1000_AL_.jpg"
 },
 {
   "Title": "The 100",
   "Mood": "adventure",
   "Your Rating": 9,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.8,
   "Genres": "Drama, Mystery, Sci-Fi",
   "Release Date": "2014-03-19",
   "Directors": "",
   "Year": 2014,
   "URL": "https://www.imdb.com/title/tt2661044/",
   "image": "https://m.media-amazon.com/images/M/MV5BNjk0ZjEzNGEtOTg5Yy00ZTU3LWE1NTQtNWI4MTJmMTlkMTVhXkEyXkFqcGdeQXVyNDc0NDgwODI@._V1_SY1000_CR0,0,666,1000_AL_.jpg"
 },
 {
   "Title": "Ellen: The Ellen DeGeneres Show",
   "Mood": "sleep",
   "Your Rating": 9,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.2,
   "Genres": "Comedy, Talk-Show",
   "Release Date": "2003-09-08",
   "Directors": "",
   "Year": 2003,
   "URL": "https://www.imdb.com/title/tt0379623/",
   "image": "https://m.media-amazon.com/images/M/MV5BODA5ZDQyMzYtZWQwMy00MDQ1LWE2OGUtNGYyNTk0Y2NhZGM4XkEyXkFqcGdeQXVyMTkzODUwNzk@._V1_SY1000_CR0,0,678,1000_AL_.jpg"
 },
 {
   "Title": "Gossip Girl",
   "Mood": "love",
   "Your Rating": 9,
   "Title Type": "tvSeries",
   "IMDb Rating": 7.4,
   "Genres": "Drama, Romance",
   "Release Date": "2007-09-19",
   "Directors": "",
   "Year": 2007,
   "URL": "https://www.imdb.com/title/tt0397442/",
   "image": "https://m.media-amazon.com/images/M/MV5BNmQ4Zjg1YWYtMTA1Mi00ZGY1LTlmN2ItYTc5ODkzNTFmYWVhXkEyXkFqcGdeQXVyNjQ0OTk1ODg@._V1_SY1000_CR0,0,776,1000_AL_.jpg"
 },
 {
   "Title": "The Crown",
   "Mood": "think",
   "Your Rating": 9,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.7,
   "Genres": "Drama, History",
   "Release Date": "2016-11-01",
   "Directors": "",
   "Year": 2016,
   "URL": "https://www.imdb.com/title/tt4786824/",
   "image": "https://m.media-amazon.com/images/M/MV5BMjAxOTA2Mjc3MF5BMl5BanBnXkFtZTgwMTMxMzIxNDM@._V1_SY1000_CR0,0,674,1000_AL_.jpg"
 },
 {
   "Title": "The Handmaid's Tale",
   "Mood": "cry",
   "Your Rating": 9,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.6,
   "Genres": "Drama, Sci-Fi",
   "Release Date": "2017-04-24",
   "Directors": "",
   "Year": 2017,
   "URL": "https://www.imdb.com/title/tt5834204/",
   "image": "https://m.media-amazon.com/images/M/MV5BMTU0MTI0MDAyM15BMl5BanBnXkFtZTgwMDg5MzYyNTM@._V1_SY1000_CR0,0,684,1000_AL_.jpg"
 },
 {
   "Title": "Pushing Daisies",
   "Mood": "laugh",
   "Your Rating": 9,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.4,
   "Genres": "Comedy, Drama, Fantasy, Mystery, Romance",
   "Release Date": "2007-10-03",
   "Directors": "",
   "Year": 2007,
   "URL": "https://www.imdb.com/title/tt0925266/",
   "image": "https://m.media-amazon.com/images/M/MV5BMTY3ODYxNjU1Nl5BMl5BanBnXkFtZTcwMTI0MTU1MQ@@._V1_.jpg"
 },
 {
   "Title": "The Good Place",
   "Mood": "laugh",
   "Your Rating": 9,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.1,
   "Genres": "Comedy, Drama, Fantasy",
   "Release Date": "2016-09-19",
   "Directors": "",
   "Year": 2016,
   "URL": "https://www.imdb.com/title/tt4955642",
   "image": "https://m.media-amazon.com/images/M/MV5BZTc2ZDQ1ODMtNDZlYS00ZmEyLThlOTQtNjg0MGFlZjkzYjhlXkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_.jpg"
 },
 {
   "Title": "Game of Thrones",
   "Mood": "adventure",
   "Your Rating": 9,
   "Title Type": "tvSeries",
   "IMDb Rating": 9.5,
   "Genres": "Action, Adventure, Drama, Fantasy, Romance",
   "Release Date": "2011-04-17",
   "Directors": "",
   "Year": 2011,
   "URL": "https://www.imdb.com/title/tt0944947/",
   "image": "https://m.media-amazon.com/images/M/MV5BMjE3NTQ1NDg1Ml5BMl5BanBnXkFtZTgwNzY2NDA0MjI@._V1_SY1000_CR0,0,674,1000_AL_.jpg"
 },
 {
   "Title": "Freaks and Geeks",
   "Mood": "laugh",
   "Your Rating": 10,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.8,
   "Genres": "Comedy, Drama",
   "Release Date": "1999-09-25",
   "Directors": "",
   "Year": 1999,
   "URL": "https://www.imdb.com/title/tt0193676/",
   "image": "https://m.media-amazon.com/images/M/MV5BZWJhOGFiZWMtYTY5Ni00NGU1LWE5OWItNzA5NThkNWUwYzc4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SY1000_CR0,0,701,1000_AL_.jpg"
 },
 {
   "Title": "Feud",
   "Mood": "think",
   "Your Rating": 10,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.6,
   "Genres": "Biography, Drama",
   "Release Date": "2017-01-11",
   "Directors": "",
   "Year": 2017,
   "URL": "https://www.imdb.com/title/tt1984119/",
   "image": "https://m.media-amazon.com/images/M/MV5BMjA2ODdhY2YtNDAzZi00MDQ5LTljZmYtMjcyZmJiY2YxOWE1L2ltYWdlXkEyXkFqcGdeQXVyNjY5NjM5MjA@._V1_SY1000_CR0,0,685,1000_AL_.jpg"
 },
 {
   "Title": "The Office",
   "Mood": "laugh",
   "Your Rating": 10,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.8,
   "Genres": "Comedy",
   "Release Date": "2005-03-24",
   "Directors": "",
   "Year": 2005,
   "URL": "https://www.imdb.com/title/tt0386676/",
   "image": "https://m.media-amazon.com/images/M/MV5BMTgzNjAzMDE0NF5BMl5BanBnXkFtZTcwNTEyMzM3OA@@._V1_SY1000_CR0,0,736,1000_AL_.jpg"
 },
 {
   "Title": "30 Rock",
   "Mood": "laugh",
   "Your Rating": 10,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.2,
   "Genres": "Comedy",
   "Release Date": "2006-10-11",
   "Directors": "",
   "Year": 2006,
   "URL": "https://www.imdb.com/title/tt0496424/",
   "image": "https://m.media-amazon.com/images/M/MV5BMTQ4NDQ4OTUzOV5BMl5BanBnXkFtZTcwMjMzMTUyNw@@._V1_.jpg"
 },
 {
   "Title": "Mad Men",
   "Mood": "big",
   "Your Rating": 10,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.6,
   "Genres": "Drama",
   "Release Date": "2007-07-19",
   "Directors": "",
   "Year": 2007,
   "URL": "https://www.imdb.com/title/tt0804503/",
   "image": "https://m.media-amazon.com/images/M/MV5BMjMwNzk5Nzg2OV5BMl5BanBnXkFtZTgwMjg1OTk1NDE@._V1_SY1000_CR0,0,685,1000_AL_.jpg"
 },
 {
   "Title": "Breaking Bad",
   "Mood": "big",
   "Your Rating": 10,
   "Title Type": "tvSeries",
   "IMDb Rating": 9.5,
   "Genres": "Crime, Drama, Thriller",
   "Release Date": "2008-01-20",
   "Directors": "",
   "Year": 2008,
   "URL": "https://www.imdb.com/title/tt0903747/",
   "image": "https://m.media-amazon.com/images/M/MV5BZDNhNzhkNDctOTlmOS00NWNmLWEyODQtNWMxM2UzYmJiNGMyXkEyXkFqcGdeQXVyNTMxMjgxMzA@._V1_.jpg"
 },
 {
   "Title": "Maniac",
   "Mood": "think",
   "Your Rating": 10,
   "Title Type": "tvMiniSeries",
   "IMDb Rating": 8.1,
   "Genres": "Comedy, Drama, Sci-Fi",
   "Release Date": "2018-09-21",
   "Directors": "",
   "Year": 2018,
   "URL": "https://www.imdb.com/title/tt5580146/",
   "image": "https://m.media-amazon.com/images/M/MV5BMjUyMDE4MzkzN15BMl5BanBnXkFtZTgwMzIwMTYzNjM@._V1_.jpg"
 },
 {
   "Title": "The Joy of Painting",
   "Mood": "sleep",
   "Your Rating": 10,
   "Title Type": "tvSeries",
   "IMDb Rating": 9.4,
   "Genres": "Documentary, Family",
   "Release Date": "1983-01-01",
   "Directors": "",
   "Year": 1983,
   "URL": "https://www.imdb.com/title/tt0383795/",
   "image": "https://m.media-amazon.com/images/M/MV5BNTk1Yjg4ODAtY2NkNi00NDljLThmMWQtOWI4NTJjNmY4NjUxL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNDQzMDg4Nzk@._V1_.jpg"
 },
 {
   "Title": "Chilling Adventures of Sabrina",
   "Mood": "dark",
   "Your Rating": 8,
   "Title Type": "tvSeries",
   "IMDb Rating": 8.0,
   "Genres": "Drama, Fantasy, Horror",
   "Release Date": "2018-10-26",
   "Directors": "",
   "Year": 2018,
   "URL": "https://www.imdb.com/title/tt7569592/",
   "image": "https://m.media-amazon.com/images/M/MV5BOTQyMDYwNDMyOV5BMl5BanBnXkFtZTgwMjM4NTIzNjM@._V1_SY1000_CR0,0,674,1000_AL_.jpg"
 }
]